export {default as Home} from "./Home"
export {default as Admin} from "./Admin"
export {default as Login} from "./Login"
export {default as Signup} from "./Signup"
export {default as Cart} from "./Cart"
export {default as Checkout} from "./CheckOut"
export {default as ProductDetail} from "./ProductDetail"